ds_course = [['Machine Learning Crash Course by Google [Free]', 'https://developers.google.com/machine-learning/crash-course'],
             ['Machine Learning A-Z by Udemy','https://www.udemy.com/course/machinelearning/'],
             ['Machine Learning by Andrew NG','https://www.coursera.org/learn/machine-learning'],
             ['Data Scientist Master Program of Simplilearn (IBM)','https://www.simplilearn.com/big-data-and-analytics/senior-data-scientist-masters-program-training'],
             ['Data Science Foundations: Fundamentals by LinkedIn','https://www.linkedin.com/learning/data-science-foundations-fundamentals-5'],
             ['Data Scientist with Python','https://www.datacamp.com/tracks/data-scientist-with-python'],
             ['Programming for Data Science with Python','https://www.udacity.com/course/programming-for-data-science-nanodegree--nd104'],
             ['Programming for Data Science with R','https://www.udacity.com/course/programming-for-data-science-nanodegree-with-R--nd118'],
             ['Introduction to Data Science','https://www.udacity.com/course/introduction-to-data-science--cd0017'],
             ['Intro to Machine Learning with TensorFlow','https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230']]

web_course = [['Django Crash course [Free]','https://youtu.be/e1IyzVyrLSU'],
              ['Python and Django Full Stack Web Developer Bootcamp','https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp'],
              ['React Crash Course [Free]','https://youtu.be/Dorf8i6lCuk'],
              ['ReactJS Project Development Training','https://www.dotnettricks.com/training/masters-program/reactjs-certification-training'],
              ['Full Stack Web Developer - MEAN Stack','https://www.simplilearn.com/full-stack-web-developer-mean-stack-certification-training'],
              ['Node.js and Express.js [Free]','https://youtu.be/Oe421EPjeBE'],
              ['Flask: Develop Web Applications in Python','https://www.educative.io/courses/flask-develop-web-applications-in-python'],
              ['Full Stack Web Developer by Udacity','https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd0044'],
              ['Front End Web Developer by Udacity','https://www.udacity.com/course/front-end-web-developer-nanodegree--nd0011'],
              ['Become a React Developer by Udacity','https://www.udacity.com/course/react-nanodegree--nd019']]

android_course = [['Android Development for Beginners [Free]','https://youtu.be/fis26HvvDII'],
                  ['Android App Development Specialization','https://www.coursera.org/specializations/android-app-development'],
                  ['Associate Android Developer Certification','https://grow.google/androiddev/#?modal_active=none'],
                  ['Become an Android Kotlin Developer by Udacity','https://www.udacity.com/course/android-kotlin-developer-nanodegree--nd940'],
                  ['Android Basics by Google','https://www.udacity.com/course/android-basics-nanodegree-by-google--nd803'],
                  ['The Complete Android Developer Course','https://www.udemy.com/course/complete-android-n-developer-course/'],
                  ['Building an Android App with Architecture Components','https://www.linkedin.com/learning/building-an-android-app-with-architecture-components'],
                  ['Android App Development Masterclass using Kotlin','https://www.udemy.com/course/android-oreo-kotlin-app-masterclass/'],
                  ['Flutter & Dart - The Complete Flutter App Development Course','https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/'],
                  ['Flutter App Development Course [Free]','https://youtu.be/rZLR5olMR64']]

ios_course = [['IOS App Development by LinkedIn','https://www.linkedin.com/learning/subscription/topics/ios'],
              ['iOS & Swift - The Complete iOS App Development Bootcamp','https://www.udemy.com/course/ios-13-app-development-bootcamp/'],
              ['Become an iOS Developer','https://www.udacity.com/course/ios-developer-nanodegree--nd003'],
              ['iOS App Development with Swift Specialization','https://www.coursera.org/specializations/app-development'],
              ['Mobile App Development with Swift','https://www.edx.org/professional-certificate/curtinx-mobile-app-development-with-swift'],
              ['Swift Course by LinkedIn','https://www.linkedin.com/learning/subscription/topics/swift-2'],
              ['Objective-C Crash Course for Swift Developers','https://www.udemy.com/course/objectivec/'],
              ['Learn Swift by Codecademy','https://www.codecademy.com/learn/learn-swift'],
              ['Swift Tutorial - Full Course for Beginners [Free]','https://youtu.be/comQ1-x2a1Q'],
              ['Learn Swift Fast - [Free]','https://youtu.be/FcsY1YPBwzQ']]

uiux_course = [['Google UX Design Professional Certificate','https://www.coursera.org/professional-certificates/google-ux-design'],
               ['UI / UX Design Specialization','https://www.coursera.org/specializations/ui-ux-design'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['UX & Web Design Master Course: Strategy, Design, Development','https://www.udemy.com/course/ux-web-design-master-course-strategy-design-development/'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['DESIGN RULES: Principles + Practices for Great UI Design','https://www.udemy.com/course/design-rules/'],
               ['Become a UX Designer by Udacity','https://www.udacity.com/course/ux-designer-nanodegree--nd578'],
               ['Adobe XD Tutorial: User Experience Design Course [Free]','https://youtu.be/68w2VwalD5w'],
               ['Adobe XD for Beginners [Free]','https://youtu.be/WEljsc2jorI'],
               ['Adobe XD in Simple Way','https://learnux.io/course/adobe-xd']]

marketing_course = [['Content Marketing Certification by HubSpot [Free]', 'https://academy.hubspot.com/courses/content-marketing'],
                    ['SEO Training by Moz Academy','https://moz.com/training/seo-essential-training'],
                    ['Social Media Marketing by Udemy','https://www.udemy.com/course/social-media-marketing-mastery/'],
                    ['Digital Marketing by Google [Free]', 'https://learndigital.withgoogle.com/digitalgarage/course/digital-marketing'],
                    ['Marketing Analytics by Coursera','https://www.coursera.org/learn/marketing-analytics'],
                    ['The Strategy of Content Marketing by Coursera','https://www.coursera.org/learn/content-marketing'],
                    ['Email Marketing Certified by HubSpot [Free]','https://academy.hubspot.com/courses/email-marketing'],
                    ['Advanced Social Media Strategy by Hootsuite','https://hootsuite.com/pages/education/advanced-social-media-strategy'],
                    ['PPC Advertising by LinkedIn Learning','https://www.linkedin.com/learning/pay-per-click-advertising'],
                    ['Marketing Fundamentals by edX','https://www.edx.org/course/marketing-fundamentals']]
finance_course = [['Financial Markets by Yale (Coursera)','https://www.coursera.org/learn/financial-markets'],
                  ['Investment Management by Coursera','https://www.coursera.org/learn/investment-management'],
                  ['Corporate Finance by edX','https://www.edx.org/course/introduction-to-corporate-finance'],
                  ['Financial Modeling and Valuation by Udemy','https://www.udemy.com/course/financial-modeling-valuation/'],
                  ['Finance for Non-Finance Professionals by Coursera','https://www.coursera.org/learn/finance-for-non-finance'],
                  ['Risk Management by Udemy','https://www.udemy.com/course/risk-management/'],
                  ['Investment Banking by Wall Street Prep','https://www.wallstreetprep.com/courses/investment-banking-bootcamp/'],
                  ['Financial Accounting by Coursera','https://www.coursera.org/learn/wharton-accounting'],
                  ['Excel Skills for Business by Coursera','https://www.coursera.org/specializations/excel'],
                  ['Financial Risk Manager by GARP (FRM Certification)','https://www.garp.org/frm']]
hr_course = [['Strategic HR Leadership by Coursera','https://www.coursera.org/learn/strategic-hr-leadership'],
             ['Human Resource Management by Udemy','https://www.udemy.com/course/human-resources-management/'],
             ['People Management by Coursera','https://www.coursera.org/learn/people-management'],
             ['Talent Acquisition by LinkedIn Learning','https://www.linkedin.com/learning/talent-acquisition'],
             ['HR Analytics by Udemy','https://www.udemy.com/course/hr-analytics/'],
             ['Learning and Development by LinkedIn Learning','https://www.linkedin.com/learning/learning-and-development'],
             ['Compensation and Benefits by Udemy','https://www.udemy.com/course/compensation-and-benefits/'],
             ['Conflict Resolution by LinkedIn Learning','https://www.linkedin.com/learning/mediation-and-conflict-resolution'],
             ['Employee Relations by Coursera','https://www.coursera.org/learn/employee-relations'],
             ['HR Policies by edX','https://www.edx.org/course/understanding-human-resource-management']]
healthcare_course = [['Introduction to Healthcare by Coursera','https://www.coursera.org/learn/intro-healthcare'],
                     ['Health Informatics by edX','https://www.edx.org/professional-certificate/healthcare-informatics'],
                     ['Healthcare Administration by Udemy','https://www.udemy.com/course/healthcare-administration/'],
                     ['Public Health by Coursera','https://www.coursera.org/specializations/public-health'],
                     ['Medical Billing and Coding by Udemy','https://www.udemy.com/course/medical-billing-coding/'],
                     ['Electronic Medical Records (EMR) Training','https://www.coursera.org/learn/electronic-medical-records'],
                     ['Clinical Research by Coursera','https://www.coursera.org/learn/clinical-research'],
                     ['Health Economics by edX','https://www.edx.org/course/healthcare-economics'],
                     ['Health Analytics by Udemy','https://www.udemy.com/course/healthcare-data-analytics/'],
                     ['Healthcare Compliance by Udemy','https://www.udemy.com/course/healthcare-compliance-certification/']]
education_course = [['Learning How to Learn by Coursera [Free]', 'https://www.coursera.org/learn/learning-how-to-learn'],
                    ['Instructional Design Foundations by LinkedIn Learning','https://www.linkedin.com/learning/instructional-design-foundations-and-applications'],
                    ['Classroom Management by Coursera','https://www.coursera.org/learn/classroom-management'],
                    ['Curriculum Development by Udemy','https://www.udemy.com/course/curriculum-development/'],
                    ['Special Education by Coursera','https://www.coursera.org/learn/special-education'],
                    ['Early Childhood Education by Udemy','https://www.udemy.com/course/early-childhood-education/'],
                    ['Educational Technology by edX','https://www.edx.org/course/technology-for-education'],
                    ['E-Learning Essentials by LinkedIn Learning','https://www.linkedin.com/learning/e-learning-essentials'],
                    ['Instructional Design for e-Learning by Udemy','https://www.udemy.com/course/instructional-design/'],
                    ['Behavior Management by LinkedIn Learning','https://www.linkedin.com/learning/behavior-management-in-the-classroom']]
law_course = [['Introduction to American Law by Coursera','https://www.coursera.org/learn/american-law'],
              ['Intellectual Property Law by Udemy','https://www.udemy.com/course/intellectual-property-law-for-business/'],
              ['Contract Law by edX','https://www.edx.org/course/contract-law'],
              ['Corporate Law by Coursera','https://www.coursera.org/learn/corporate-law'],
              ['Employment Law by Udemy','https://www.udemy.com/course/employment-law-compliance/'],
              ['Legal Research by Coursera','https://www.coursera.org/learn/legal-research'],
              ['Litigation and Trial Practice by Udemy','https://www.udemy.com/course/litigation-and-trial-practice/'],
              ['Mediation and Conflict Resolution by edX','https://www.edx.org/course/mediation-and-conflict-resolution'],
              ['Criminal Law by Coursera','https://www.coursera.org/learn/criminal-law'],
              ['Compliance Law by Coursera','https://www.coursera.org/learn/compliance-law']]
engineering_course = [['Mechanical Engineering by Coursera','https://www.coursera.org/specializations/mechanical-engineering'],
                      ['AutoCAD 2D and 3D Practice by Udemy','https://www.udemy.com/course/autocad-2d-and-3d-practice-drawings/'],
                      ['Electrical Engineering Fundamentals by Coursera','https://www.coursera.org/specializations/electrical-engineering'],
                      ['Civil Engineering by edX','https://www.edx.org/professional-certificate/civil-engineering'],
                      ['SolidWorks Training by Udemy','https://www.udemy.com/course/solidworks-training/'],
                      ['MATLAB for Engineers by Coursera','https://www.coursera.org/learn/matlab'],
                      ['FEA Analysis by Udemy','https://www.udemy.com/course/finite-element-analysis/'],
                      ['Project Management for Engineers by edX','https://www.edx.org/course/project-management-for-engineers'],
                      ['Manufacturing Process Control by Coursera','https://www.coursera.org/learn/process-control'],
                      ['CAD Modeling by Udemy','https://www.udemy.com/course/cad-modelling/']]
sales_course = [['Sales Training by Udemy','https://www.udemy.com/course/sales-training/'],
                ['Negotiation Mastery by edX','https://www.edx.org/course/negotiation-mastery'],
                ['B2B Sales by LinkedIn Learning','https://www.linkedin.com/learning/b2b-sales'],
                ['Account Management by Coursera','https://www.coursera.org/learn/account-management'],
                ['Sales Forecasting by Udemy','https://www.udemy.com/course/sales-forecasting/'],
                ['Cold Calling Mastery by Udemy','https://www.udemy.com/course/cold-calling/'],
                ['CRM Training by Coursera','https://www.coursera.org/learn/customer-relationship-management'],
                ['Closing Sales by LinkedIn Learning','https://www.linkedin.com/learning/closing-sales'],
                ['Lead Generation by Udemy','https://www.udemy.com/course/lead-generation/'],
                ['Territory Management by Udemy','https://www.udemy.com/course/territory-management/']]
design_course = [['Photoshop Mastery by Udemy','https://www.udemy.com/course/photoshop-mastery/'],
                 ['Graphic Design by LinkedIn Learning','https://www.linkedin.com/learning/graphic-design-tips-and-tricks'],
                 ['UI/UX Design by Coursera','https://www.coursera.org/specializations/ui-ux-design'],
                 ['Motion Graphics by Udemy','https://www.udemy.com/course/motion-graphics/'],
                 ['Typography by Udemy','https://www.udemy.com/course/typography/'],
                 ['Adobe Illustrator by LinkedIn Learning','https://www.linkedin.com/learning/adobe-illustrator'],
                 ['Figma Design by Udemy','https://www.udemy.com/course/figma-for-designers/'],
                 ['Prototyping with Sketch by Udemy','https://www.udemy.com/course/sketch-design/'],
                 ['Wireframing with Adobe XD by Udemy','https://www.udemy.com/course/adobe-xd-wireframing/'],
                 ['Branding for Designers by Coursera','https://www.coursera.org/learn/branding-for-designers']]
construction_course = [['Construction Project Management by Coursera','https://www.coursera.org/learn/construction-project-management'],
                       ['Construction Management by Udemy','https://www.udemy.com/course/construction-management/'],
                       ['Cost Estimation in Construction by LinkedIn Learning','https://www.linkedin.com/learning/construction-cost-estimating'],
                       ['Construction Safety and Health by Coursera','https://www.coursera.org/learn/construction-safety-health'],
                       ['Contract Management and Procurement by edX','https://www.edx.org/course/contract-management'],
                       ['Construction Scheduling by Udemy','https://www.udemy.com/course/construction-scheduling/'],
                       ['Project Planning and Scheduling for Construction by Coursera','https://www.coursera.org/learn/construction-planning'],
                       ['Risk Management in Construction Projects by edX','https://www.edx.org/course/risk-management-in-construction-projects'],
                       ['Quality Control in Construction by Udemy','https://www.udemy.com/course/quality-control-in-construction/'],
                       ['Building Codes and Regulations by LinkedIn Learning','https://www.linkedin.com/learning/building-codes-and-regulations']]

